### ISSUE TITLE
Bug: Typo in the NotifyMe file

### ISSUE THREAD

**Issue by atapas** [atapas/notifyme#20]
Here is a Typo: https://github.com/atapas/notifyme/blob/6574cbe72ca9eb584e144ef77b3a5fc522796a4e/NotifyMe.js#L203

It should have a proper proptype validation but it says prototype.

**Comment by Padmanabh82** [comment]
is this issue solved ?? can i work on it ??

**Comment by atapas** [comment]
> is this issue solved ?? can i work on it ??

Assigned

**Comment by Padmanabh82** [comment]
but it doesn't have static folder ,public folder many things are missing

**Comment by Padmanabh82** [comment]
how to work on it
??

**Comment by atapas** [comment]
You can make the code changed and test it along with a basic create react app instance. @SankalpaFernando do you want to put more info how you tested your earlier PR changes?

**Comment by SankalpaFernando** [comment]
@Padmanabh82 I used a react template that was created by using create-react-app and then I created a folder called notifyme inside /src folder and inside notifyme folder I initiated an empty git repository and pulled the forked repository into the empty repository. Then for the testing, I imported the NotifyMe component from NotifyMe.js to index.js in my react-template.

**Comment by atapas** [comment]
Hi @Padmanabh82 , I see the issue has been fixed by @SankalpaFernando as part of issue # 22. Hence I will be closing this one. Please feel free to pick up anything from here of from https://github.com/atapas/webapis-playground repo.
